#The view_annotations flag must be false to work with FOSRestBundle
sensio_framework_extra:
    view:
        annotations: false

doctrine:
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
            activecollab:
                connection: activecollab
            beethoven:
                connection: beethoven
