parameters:
#    oh_seven_beethoven_api.example.class: OhSeven\Beethoven\ApiBundle\Example

services:
#    oh_seven_beethoven_api.example:
#        class: %oh_seven_beethoven_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
