parameters:
    oh_seven_beethoven_api.board.handler.class: OhSeven\Beethoven\ApiBundle\Handler\BoardHandler
    oh_seven_beethoven_api.board.class: OhSeven\Beethoven\ApiBundle\Entity\Board

services:
    oh_seven_beethoven_api.board.repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine.orm.beethoven_entity_manager
        factory_method: getRepository
        arguments: [ "%oh_seven_beethoven_api.board.class%" ]

    oh_seven_beethoven_api.board.handler:
        class: "%oh_seven_beethoven_api.board.handler.class%"
        arguments: [ "@oh_seven_beethoven_api.board.repository" ]
